module.exports = {
  HTTP2_SESSION_SEND_HEADERS : 'S',
  HTTP2_SESSION_RECV_HEADERS : 'R',
  HTTP2_SESSION_RECV_DATA : 'D',
  HTTP2_SESSION_RECV_PUSH_PROMISE : 'P',
  HTTP2_STREAM_ADOPTED_PUSH_STREAM : 'A',
  OTHER : '*'
};
